name: Build
run-name: Build the game
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: build docker image
        run: docker build . --file Dockerfile --tag adam:latest
