name: Build
run-name: Build the game
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: build docker image
        run: docker build . --file Dockerfile --tag game:latest

      - name: View Progress
        run: echo "Run the export action to publish the game."
